# Generated by Django 5.0.1 on 2025-12-06 14:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, help_text='Required. Used for login.', max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, help_text="User's first name (e.g., Ahmed)", max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, help_text="User's last name (e.g., Ali)", max_length=50, verbose_name='last name')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number (e.g., +201234567890)', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('agent', 'Agent')], db_index=True, default='agent', help_text='User role: admin (full access) or agent (limited access)', max_length=20, verbose_name='role')),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture (recommended: 300x300px, max 2MB)', null=True, upload_to='avatars/%Y/%m/', verbose_name='profile picture')),
                ('job_title', models.CharField(blank=True, help_text='e.g., Sales Manager, Customer Service Agent', max_length=100, verbose_name='job title')),
                ('department', models.CharField(blank=True, help_text='e.g., Sales, Customer Support, Administration', max_length=100, verbose_name='department')),
                ('total_leads_assigned', models.PositiveIntegerField(default=0, help_text='Total number of leads assigned to this user', verbose_name='total leads assigned')),
                ('total_leads_converted', models.PositiveIntegerField(default=0, help_text='Number of leads converted to patients', verbose_name='total leads converted')),
                ('total_leads_won', models.PositiveIntegerField(default=0, help_text='Number of leads that resulted in successful sales', verbose_name='total leads won')),
                ('login_count', models.PositiveIntegerField(default=0, help_text='Number of times user has logged in', verbose_name='login count')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last login', null=True, verbose_name='last login IP')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when user account was created', verbose_name='date joined')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time user profile was updated', verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Short bio or description (max 500 characters)', max_length=500, verbose_name='biography')),
                ('date_of_birth', models.DateField(blank=True, help_text="User's birthday", null=True, verbose_name='date of birth')),
                ('address', models.CharField(blank=True, help_text='Street address', max_length=255, verbose_name='address')),
                ('city', models.CharField(blank=True, help_text='City name', max_length=100, verbose_name='city')),
                ('country', models.CharField(blank=True, default='Egypt', help_text='Country name', max_length=100, verbose_name='country')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive notifications via email', verbose_name='email notifications')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Receive notifications via SMS', verbose_name='SMS notifications')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', help_text='UI theme preference', max_length=20, verbose_name='theme')),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', help_text='Preferred language', max_length=10, verbose_name='language')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=255, verbose_name='LinkedIn profile')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL', max_length=255, verbose_name='Twitter profile')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(help_text='The user this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx'),
        ),
    ]
