# Generated by Django 5.0.1 on 2025-12-06 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The clinic/company this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='en', help_text='Preferred language', max_length=10, verbose_name='language'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['company', 'role'], name='accounts_us_company_8958d5_idx'),
        ),
    ]
