# Generated by Django 5.0.1 on 2025-12-10 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('leads', '0003_alter_lead_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WoztellConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Woztell API key for authentication', max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(help_text='Woztell API secret key', max_length=255, verbose_name='API Secret')),
                ('channel_id', models.CharField(help_text='WhatsApp Business channel ID from Woztell', max_length=100, verbose_name='Channel ID')),
                ('webhook_secret', models.CharField(help_text='Secret key to validate incoming webhooks', max_length=255, verbose_name='Webhook Secret')),
                ('webhook_url', models.URLField(blank=True, help_text='Full webhook URL (for reference)', max_length=500, null=True, verbose_name='Webhook URL')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.OneToOneField(help_text='Company that owns this configuration', on_delete=django.db.models.deletion.CASCADE, related_name='woztell_config', to='core.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Woztell Configuration',
                'verbose_name_plural': 'Woztell Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], default='whatsapp', help_text='Type of communication channel', max_length=20, verbose_name='Channel Type')),
                ('channel_id', models.CharField(blank=True, help_text='External channel ID from provider', max_length=255, null=True, verbose_name='Channel ID')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of last message in this channel', null=True, verbose_name='Last Message At')),
                ('unread_count', models.PositiveIntegerField(default=0, help_text='Number of unread messages', verbose_name='Unread Count')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this channel is active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='core.company', verbose_name='Company')),
                ('lead', models.ForeignKey(help_text='Lead associated with this channel', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'ordering': ['-last_message_at'],
                'indexes': [models.Index(fields=['company', 'is_active', '-last_message_at'], name='whatsapp_ch_company_f95155_idx')],
                'unique_together': {('lead', 'channel_type')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], help_text='Message direction (incoming or outgoing)', max_length=10, verbose_name='Direction')),
                ('content', models.TextField(help_text='Text content of the message', verbose_name='Content')),
                ('media_url', models.URLField(blank=True, help_text='URL to media file (if any)', max_length=500, null=True, verbose_name='Media URL')),
                ('media_type', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], help_text='Type of media attachment', max_length=20, null=True, verbose_name='Media Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', help_text='Delivery status of the message', max_length=20, verbose_name='Status')),
                ('woztell_message_id', models.CharField(blank=True, help_text='Message ID from Woztell API', max_length=255, null=True, verbose_name='Woztell Message ID')),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed', null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('lead', models.ForeignKey(help_text='Lead associated with this message', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='leads.lead', verbose_name='Lead')),
                ('user', models.ForeignKey(blank=True, help_text='User who sent this message (null for incoming)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', 'direction', '-created_at'], name='whatsapp_me_lead_id_b491c9_idx'), models.Index(fields=['status', '-created_at'], name='whatsapp_me_status_c5a0c4_idx')],
            },
        ),
    ]
