# Generated by Django 5.0.1 on 2025-12-06 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Source name (e.g. WhatsApp, Facebook)', max_length=100, unique=True)),
                ('icon', models.CharField(help_text='FontAwesome icon class (e.g. fab fa-whatsapp)', max_length=50)),
                ('color', models.CharField(default='#667eea', help_text='Hex color code (e.g. #25D366 for WhatsApp green)', max_length=7)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('is_active', models.BooleanField(default=True, help_text='Is this source active?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead Source',
                'verbose_name_plural': 'Lead Sources',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company/Clinic name', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly name (auto-generated)', max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='companies/logos/')),
                ('description', models.TextField(blank=True, help_text='Brief description about the company')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=17)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Company website', validators=[django.core.validators.URLValidator()])),
                ('address', models.TextField(blank=True, help_text='Physical address')),
                ('working_hours', models.CharField(blank=True, help_text='e.g. 9 AM - 5 PM, Sat-Thu', max_length=200)),
                ('timezone', models.CharField(default='Africa/Cairo', help_text='Company timezone', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is company active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='core_compan_slug_9ea5c6_idx'), models.Index(fields=['is_active'], name='core_compan_is_acti_f26725_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Stage name (e.g. Contacted, Qualified)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly name (auto-generated)', max_length=100, unique=True)),
                ('stage_type', models.CharField(choices=[('lead', 'Lead'), ('patient', 'Patient'), ('closed', 'Closed')], default='lead', help_text='Stage type for filtering', max_length=20)),
                ('color', models.CharField(default='#667eea', help_text='Hex color code for UI display', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class (e.g. fas fa-phone)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Stage description (what happens in this stage)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in Kanban (lower numbers = left)')),
                ('is_active', models.BooleanField(default=True, help_text='Is this stage active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead Stage',
                'verbose_name_plural': 'Lead Stages',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['stage_type'], name='core_leadst_stage_t_0a1515_idx'), models.Index(fields=['order'], name='core_leadst_order_dfedec_idx')],
            },
        ),
    ]
