# Generated by Django 5.0.1 on 2025-12-08 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Lead's full name", max_length=200)),
                ('phone', models.CharField(db_index=True, help_text='Phone number in international format', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', help_text='Current internal status', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='How urgent is this lead?', max_length=10)),
                ('next_follow_up', models.DateTimeField(blank=True, db_index=True, help_text='When is the next follow-up scheduled?', null=True)),
                ('notes', models.TextField(blank=True, help_text='General notes about this lead')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorizing leads (JSON array)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When was this lead created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When was this lead last updated')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Which agent is responsible for this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(help_text='Which company/clinic owns this lead', on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.company')),
                ('source', models.ForeignKey(help_text='Where did this lead come from?', on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='core.leadsource')),
                ('stage', models.ForeignKey(help_text='Current stage in the lead lifecycle', on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='core.leadstage')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('status_changed', 'Status Changed'), ('stage_changed', 'Stage Changed'), ('note_added', 'Note Added'), ('contacted', 'Contacted'), ('email_sent', 'Email Sent'), ('call_logged', 'Call Logged')], help_text='Type of activity/action', max_length=30)),
                ('description', models.TextField(help_text='Human-readable description of what happened')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When did this activity occur')),
                ('user', models.ForeignKey(blank=True, help_text='Who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(help_text='Which lead this activity is for', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Note text/content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When was this note created')),
                ('lead', models.ForeignKey(help_text='Which lead this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes_set', to='leads.lead')),
                ('user', models.ForeignKey(help_text='Who wrote this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'status'], name='leads_lead_company_2d29e3_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'stage'], name='leads_lead_company_ea44b9_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'assigned_to'], name='leads_lead_company_d29de2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_follow_up'], name='leads_lead_next_fo_b18d27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('company', 'phone')},
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['lead', '-created_at'], name='leads_activ_lead_id_b402c8_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', '-created_at'], name='leads_activ_user_id_26c803_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['lead', '-created_at'], name='leads_note_lead_id_5425a8_idx'),
        ),
    ]
