# Generated by Django 5.0.1 on 2025-12-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_tags'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_company_2d29e3_idx',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
    ]
